### ISSUE TITLE
Assign theme colors to variables in tailwind.config.js

### ISSUE THREAD

**Issue by thehackergpt** [Hacker-GPT/HackerGPT#10]
Currently colors like `dark:bg-[#202123]` are directly in the classes which makes it difficult to maintain the code.

ACC:
- [x] Identify all used colors
- [x] Move them to tailwind.config.js in the theme section

https://tailwindcss.com/docs/theme

**Comment by Fx64b** [comment]
Also added `prettier` configuration with the `prettier-plugin-tailwindcss` that automatically sorts tailwind classnames.
