### ISSUE TITLE
Replace Twitter icon with X icon

### ISSUE THREAD

**Issue by Fx64b** [Hacker-GPT/HackerGPT#10]
![Image](https://user-images.githubusercontent.com/90456762/278062973-9ebc629d-4885-41a9-8d9d-082d8d1fc8ae.png)

ACC:
- Figure out where to get the X icon from
- Replace it with the Twitter icon

**Comment by thehackergpt** [comment]
Resolved by implementing the SVG version of the X icon from tabler-icons.

![Image](https://github.com/Hacker-GPT/HackerGPT/assets/144740362/ada4b58d-14e3-4ff1-9d28-f194ada0dd08)
