### ISSUE TITLE
About the Open-Source Nature of the Project

### ISSUE THREAD

**Issue by favarete** [Hacker-GPT/HackerGPT#160]
Hey guys, great project. I experimented a little and it works really well!

I have an honest question, hope I don't sound rude. 

It's just the front-end that will be open source and the entire API, the model, and everything that's needed for it to work, will be a paid service?

**Comment by thehackergpt** [comment]
Hi. Thanks for trying out our project and for your question.

To simplify, yes, the front-end of HackerGPT is open source for everyone to see and use. For the API, model, and other functionalities, we plan to make it a paid service. In the future, we aim to offer most of HackerGPT's functionalities just by providing an API key, including some specific plugins. Our goal is to offer as much functionality as possible for free while running HackerGPT locally. If we have the resources to provide additional functionalities for free, we will certainly do so. It might take some time, as our team is small, but with the help of other developers and the community, we're confident we can create a lot of free features for everyone to enjoy!

**Comment by thehackergpt** [comment]
The main reason for making HackerGPT open source is to show how it works and how users' data is being used. By making the code transparent, we aim to build trust with our users and provide a better understanding of the platform's functionalities.

**Comment by favarete** [comment]
> The main reason for making HackerGPT open source is to show how it works and how users' data is being used. By making the code transparent, we aim to build trust with our users and provide a better understanding of the platform's functionalities.

That's a really respectful way of thinking about software. Congrats on the project and a bright future to everyone :fist_oncoming:
