### ISSUE TITLE
using with local llm

### ISSUE THREAD

**Issue by ArchanaNarayanan843** [Hacker-GPT/HackerGPT#231]
### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

### 🐛 Bug Description

can we use this with other open source llm models instead of gpt
if we can do it, how to make it work

**Comment by thehackergpt** [comment]
HackerGPT does not use GPT for its HackerGPT and HackerGPT Pro models. It only uses GPT for plugins. If you want to switch to other open-source models that are already being used, you will need to edit the following environment variables:

```
SECRET_OPENROUTER_API_KEY=YOUR_OPENROUTER_API_KEY

OPENROUTER_TRANSLATION_MODEL=gryphe/mythomax-l2-13b

OPENROUTER_HACKERGPT_DEFAULT_MODEL=nousresearch/nous-hermes-2-mixtral-8x7b-dpo

OPENROUTER_HACKERGPT_ENHANCE_MODEL=mistralai/mistral-medium

OPENROUTER_HACKERGPT_PRO_MODEL=mistralai/mistral-large.
```
