### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by KateWasHere001** [Hacker-GPT/HackerGPT#30]
http://localhost:3000

download, install, login are ok.
But it shows "Internal Server Error" every time when try to input text.
How to fix that ?

**Comment by thehackergpt** [comment]
Hi @KateWasHere001 

Thanks for reporting this issue, and I'm sorry for the inconvenience it's causing. It's possible that the "Internal Server Error" might be related to our environment variables. We recently realized that our documentation on environment variables is outdated, and this could be contributing to the problem.

To help us better address your issue, could you please provide the following details?

1. The specific steps you're following when the error occurs.
2. Any relevant logs or error messages that appear.

**Comment by anonfaded** [comment]
> http://localhost:3000
> 
> download, install, login are ok. But it shows "Internal Server Error" every time when try to input text. How to fix that ?

Bro thats probably due to the api which is a paid feature, I also got similar issue and we can't send messages from local machine i guess.
