### ISSUE TITLE
Refine Logic for Conditional Display of "Upgrade to Plus" Button

### ISSUE THREAD

**Issue by thehackergpt** [Hacker-GPT/HackerGPT#55]
Update the existing front-end logic to defer the display of the "Upgrade to Plus" button until after a user's subscription status has been verified. The button should remain hidden until the check is complete, ensuring it is only shown to non-Plus users.
    

![Image](https://github.com/Hacker-GPT/HackerGPT/assets/144740362/fc5a96a6-be57-4cbf-9eab-2e8a78c80b91)

## ACC:

- [x] The "Upgrade to Plus" button remains hidden during the initial page load.
- [x] Modify the existing subscription check logic to function asynchronously, ensuring the UI only updates after the check is complete.
- [x] The button is displayed only if the user is confirmed to not be a Plus subscriber.
- [x] User experience should not be disrupted by the subscription check, and there should be no flicker effect of the button appearing and then disappearing.

**Comment by Fx64b** [comment]
It would make sense to pre-fetch this status and then store it in a state to avoid fetching this state multiple times.
