### ISSUE TITLE
Create a /tools or /help option

### ISSUE THREAD

**Issue by Fx64b** [Hacker-GPT/HackerGPT#62]
Create a `/tools` or `/help` option so users can get an overview of the available tools and commands.

(Idea by https://twitter.com/HCR27968837 on twitter)
![image](https://github.com/Hacker-GPT/HackerGPT/assets/90456762/98569c96-7f39-491e-92e1-5535bf4088dc)

ACC:
- [x] add `/tools` or `/help` option that displays all available tools and additional information on how to use HackerGPT
- [x] add all available tools and additional information on Github and about-us page.

**Comment by thehackergpt** [comment]
- [ ] add all available tools and additional information on Github and about-us page.

**Comment by thehackergpt** [comment]
https://github.com/Hacker-GPT/HackerGPT/pull/67/
