### ISSUE TITLE
Fix Tool Select component

### ISSUE THREAD

**Issue by Fx64b** [Hacker-GPT/HackerGPT#90]
Improve the tool select component, especially on Firefox:
![image](https://github.com/Hacker-GPT/HackerGPT/assets/90456762/301656bc-f205-4d48-aa0a-9ee3a794438c)

Acc:
- [x] Evaluate whether we should code it our self or use an existing one
- [x] Implement the improved tool select component and ensure it works on both Firefox and Chromium based browsers
- [x] Enable the activation of the Plus popup upon user interaction with the plus tool.
- [ ] Incorporate a lock icon for Plus tools to enhance user interface clarity.

**Comment by thehackergpt** [comment]
https://headlessui.com/react/listbox

**Comment by Fx64b** [comment]
Update: white outline around all the selects is a Firefox issue

**Comment by Fx64b** [comment]
Regarding the last task to add icons for plus user tools: https://stackoverflow.com/a/70093825
Apparently it is not possible to render icons in a normal `<select>`. 
For now I just disabled the premium tool options when the user is not premium.
However, we can properly implement that in #96 

The code I came up with for now is:
```ts
    {
      name: t('Subfinder: Locate Subdomains'),
      value: ToolID.SUBFINDER,
      isPremium: false,
    },
    {
      name: t('Katana: Crawl Websites'),
      value: ToolID.KATANA,
      isPremium: true,
    },
   {
     ...
   }
````
--------

```tsx
{tool.isPremium && !isPremium && (
    <IconLock size={14} />
)}
````

@thehackergpt
